// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: auth/api.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_api_proto protoreflect.FileDescriptor

const file_auth_api_proto_rawDesc = "" +
	"\n" +
	"\x0eauth/api.proto\x12\x10backend.auth.api\x1a\x1cgoogle/api/annotations.proto\x1a\x0fauth/data.proto2\xd4\x10\n" +
	"\vAuthService\x12n\n" +
	"\bRegister\x12!.backend.auth.api.RegisterRequest\x1a\".backend.auth.api.RegisterResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/api/v1/register\x12b\n" +
	"\x05Login\x12\x1e.backend.auth.api.LoginRequest\x1a\x1f.backend.auth.api.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12\x7f\n" +
	"\fRefreshToken\x12%.backend.auth.api.RefreshTokenRequest\x1a&.backend.auth.api.RefreshTokenResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/refresh-token\x12\x83\x01\n" +
	"\rResetPassword\x12&.backend.auth.api.ResetPasswordRequest\x1a'.backend.auth.api.ResetPasswordResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/reset-password\x12\x8f\x01\n" +
	"\x0eChangePassword\x12'.backend.auth.api.ChangePasswordRequest\x1a(.backend.auth.api.ChangePasswordResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/private/change-password\x12\x90\x01\n" +
	"\x11UpdateUserProfile\x12*.backend.auth.api.UpdateUserProfileRequest\x1a+.backend.auth.api.UpdateUserProfileResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/private/profile\x12\x84\x01\n" +
	"\x0eGetUserProfile\x12'.backend.auth.api.GetUserProfileRequest\x1a(.backend.auth.api.GetUserProfileResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/private/profile\x12\x80\x01\n" +
	"\rVerifyAccount\x12&.backend.auth.api.VerifyAccountRequest\x1a'.backend.auth.api.VerifyAccountResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/private/verify\x12\x90\x01\n" +
	"\x11DeactivateAccount\x12*.backend.auth.api.DeactivateAccountRequest\x1a+.backend.auth.api.DeactivateAccountResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/private/deactivate\x12\x8f\x01\n" +
	"\x10CreatePermission\x12).backend.auth.api.CreatePermissionRequest\x1a*.backend.auth.api.CreatePermissionResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/admin/permissions\x12\x86\x01\n" +
	"\x0eListPermission\x12'.backend.auth.api.ListPermissionRequest\x1a(.backend.auth.api.ListPermissionResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/admin/permissions\x12w\n" +
	"\n" +
	"CreateUser\x12#.backend.auth.api.CreateUserRequest\x1a$.backend.auth.api.CreateUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/admin/users\x12n\n" +
	"\bListUser\x12!.backend.auth.api.ListUserRequest\x1a\".backend.auth.api.ListUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/admin/users\x12\x8f\x01\n" +
	"\x0eRegisterDevice\x12'.backend.auth.api.RegisterDeviceRequest\x1a(.backend.auth.api.RegisterDeviceResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/private/register-device\x12\x97\x01\n" +
	"\x10UnregisterDevice\x12).backend.auth.api.UnregisterDeviceRequest\x1a*.backend.auth.api.UnregisterDeviceResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/private/unregister-device\x12x\n" +
	"\n" +
	"ListDevice\x12#.backend.auth.api.ListDeviceRequest\x1a$.backend.auth.api.ListDeviceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/private/devicesB\xb1\x01\n" +
	"\x14com.backend.auth.apiB\bApiProtoP\x01Z-github.com/quangdangfit/goauth/proto/api/auth\xa2\x02\x03BAA\xaa\x02\x10Backend.Auth.Api\xca\x02\x10Backend\\Auth\\Api\xe2\x02\x1cBackend\\Auth\\Api\\GPBMetadata\xea\x02\x12Backend::Auth::Apib\x06proto3"

var file_auth_api_proto_goTypes = []any{
	(*RegisterRequest)(nil),           // 0: backend.auth.api.RegisterRequest
	(*LoginRequest)(nil),              // 1: backend.auth.api.LoginRequest
	(*RefreshTokenRequest)(nil),       // 2: backend.auth.api.RefreshTokenRequest
	(*ResetPasswordRequest)(nil),      // 3: backend.auth.api.ResetPasswordRequest
	(*ChangePasswordRequest)(nil),     // 4: backend.auth.api.ChangePasswordRequest
	(*UpdateUserProfileRequest)(nil),  // 5: backend.auth.api.UpdateUserProfileRequest
	(*GetUserProfileRequest)(nil),     // 6: backend.auth.api.GetUserProfileRequest
	(*VerifyAccountRequest)(nil),      // 7: backend.auth.api.VerifyAccountRequest
	(*DeactivateAccountRequest)(nil),  // 8: backend.auth.api.DeactivateAccountRequest
	(*CreatePermissionRequest)(nil),   // 9: backend.auth.api.CreatePermissionRequest
	(*ListPermissionRequest)(nil),     // 10: backend.auth.api.ListPermissionRequest
	(*CreateUserRequest)(nil),         // 11: backend.auth.api.CreateUserRequest
	(*ListUserRequest)(nil),           // 12: backend.auth.api.ListUserRequest
	(*RegisterDeviceRequest)(nil),     // 13: backend.auth.api.RegisterDeviceRequest
	(*UnregisterDeviceRequest)(nil),   // 14: backend.auth.api.UnregisterDeviceRequest
	(*ListDeviceRequest)(nil),         // 15: backend.auth.api.ListDeviceRequest
	(*RegisterResponse)(nil),          // 16: backend.auth.api.RegisterResponse
	(*LoginResponse)(nil),             // 17: backend.auth.api.LoginResponse
	(*RefreshTokenResponse)(nil),      // 18: backend.auth.api.RefreshTokenResponse
	(*ResetPasswordResponse)(nil),     // 19: backend.auth.api.ResetPasswordResponse
	(*ChangePasswordResponse)(nil),    // 20: backend.auth.api.ChangePasswordResponse
	(*UpdateUserProfileResponse)(nil), // 21: backend.auth.api.UpdateUserProfileResponse
	(*GetUserProfileResponse)(nil),    // 22: backend.auth.api.GetUserProfileResponse
	(*VerifyAccountResponse)(nil),     // 23: backend.auth.api.VerifyAccountResponse
	(*DeactivateAccountResponse)(nil), // 24: backend.auth.api.DeactivateAccountResponse
	(*CreatePermissionResponse)(nil),  // 25: backend.auth.api.CreatePermissionResponse
	(*ListPermissionResponse)(nil),    // 26: backend.auth.api.ListPermissionResponse
	(*CreateUserResponse)(nil),        // 27: backend.auth.api.CreateUserResponse
	(*ListUserResponse)(nil),          // 28: backend.auth.api.ListUserResponse
	(*RegisterDeviceResponse)(nil),    // 29: backend.auth.api.RegisterDeviceResponse
	(*UnregisterDeviceResponse)(nil),  // 30: backend.auth.api.UnregisterDeviceResponse
	(*ListDeviceResponse)(nil),        // 31: backend.auth.api.ListDeviceResponse
}
var file_auth_api_proto_depIdxs = []int32{
	0,  // 0: backend.auth.api.AuthService.Register:input_type -> backend.auth.api.RegisterRequest
	1,  // 1: backend.auth.api.AuthService.Login:input_type -> backend.auth.api.LoginRequest
	2,  // 2: backend.auth.api.AuthService.RefreshToken:input_type -> backend.auth.api.RefreshTokenRequest
	3,  // 3: backend.auth.api.AuthService.ResetPassword:input_type -> backend.auth.api.ResetPasswordRequest
	4,  // 4: backend.auth.api.AuthService.ChangePassword:input_type -> backend.auth.api.ChangePasswordRequest
	5,  // 5: backend.auth.api.AuthService.UpdateUserProfile:input_type -> backend.auth.api.UpdateUserProfileRequest
	6,  // 6: backend.auth.api.AuthService.GetUserProfile:input_type -> backend.auth.api.GetUserProfileRequest
	7,  // 7: backend.auth.api.AuthService.VerifyAccount:input_type -> backend.auth.api.VerifyAccountRequest
	8,  // 8: backend.auth.api.AuthService.DeactivateAccount:input_type -> backend.auth.api.DeactivateAccountRequest
	9,  // 9: backend.auth.api.AuthService.CreatePermission:input_type -> backend.auth.api.CreatePermissionRequest
	10, // 10: backend.auth.api.AuthService.ListPermission:input_type -> backend.auth.api.ListPermissionRequest
	11, // 11: backend.auth.api.AuthService.CreateUser:input_type -> backend.auth.api.CreateUserRequest
	12, // 12: backend.auth.api.AuthService.ListUser:input_type -> backend.auth.api.ListUserRequest
	13, // 13: backend.auth.api.AuthService.RegisterDevice:input_type -> backend.auth.api.RegisterDeviceRequest
	14, // 14: backend.auth.api.AuthService.UnregisterDevice:input_type -> backend.auth.api.UnregisterDeviceRequest
	15, // 15: backend.auth.api.AuthService.ListDevice:input_type -> backend.auth.api.ListDeviceRequest
	16, // 16: backend.auth.api.AuthService.Register:output_type -> backend.auth.api.RegisterResponse
	17, // 17: backend.auth.api.AuthService.Login:output_type -> backend.auth.api.LoginResponse
	18, // 18: backend.auth.api.AuthService.RefreshToken:output_type -> backend.auth.api.RefreshTokenResponse
	19, // 19: backend.auth.api.AuthService.ResetPassword:output_type -> backend.auth.api.ResetPasswordResponse
	20, // 20: backend.auth.api.AuthService.ChangePassword:output_type -> backend.auth.api.ChangePasswordResponse
	21, // 21: backend.auth.api.AuthService.UpdateUserProfile:output_type -> backend.auth.api.UpdateUserProfileResponse
	22, // 22: backend.auth.api.AuthService.GetUserProfile:output_type -> backend.auth.api.GetUserProfileResponse
	23, // 23: backend.auth.api.AuthService.VerifyAccount:output_type -> backend.auth.api.VerifyAccountResponse
	24, // 24: backend.auth.api.AuthService.DeactivateAccount:output_type -> backend.auth.api.DeactivateAccountResponse
	25, // 25: backend.auth.api.AuthService.CreatePermission:output_type -> backend.auth.api.CreatePermissionResponse
	26, // 26: backend.auth.api.AuthService.ListPermission:output_type -> backend.auth.api.ListPermissionResponse
	27, // 27: backend.auth.api.AuthService.CreateUser:output_type -> backend.auth.api.CreateUserResponse
	28, // 28: backend.auth.api.AuthService.ListUser:output_type -> backend.auth.api.ListUserResponse
	29, // 29: backend.auth.api.AuthService.RegisterDevice:output_type -> backend.auth.api.RegisterDeviceResponse
	30, // 30: backend.auth.api.AuthService.UnregisterDevice:output_type -> backend.auth.api.UnregisterDeviceResponse
	31, // 31: backend.auth.api.AuthService.ListDevice:output_type -> backend.auth.api.ListDeviceResponse
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_auth_api_proto_init() }
func file_auth_api_proto_init() {
	if File_auth_api_proto != nil {
		return
	}
	file_auth_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_api_proto_rawDesc), len(file_auth_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_api_proto_goTypes,
		DependencyIndexes: file_auth_api_proto_depIdxs,
	}.Build()
	File_auth_api_proto = out.File
	file_auth_api_proto_goTypes = nil
	file_auth_api_proto_depIdxs = nil
}
