/**
 * @fileoverview gRPC-Web generated client stub for backend.auth.api
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: auth/api.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as auth_data_pb from '../auth/data_pb'; // proto import: "auth/data.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/Register',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.RegisterRequest,
    auth_data_pb.RegisterResponse,
    (request: auth_data_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.RegisterResponse.deserializeBinary
  );

  register(
    request: auth_data_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.RegisterResponse>;

  register(
    request: auth_data_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.RegisterResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.RegisterResponse>;

  register(
    request: auth_data_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.RegisterResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.LoginRequest,
    auth_data_pb.LoginResponse,
    (request: auth_data_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.LoginResponse.deserializeBinary
  );

  login(
    request: auth_data_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.LoginResponse>;

  login(
    request: auth_data_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.LoginResponse>;

  login(
    request: auth_data_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorRefreshToken = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/RefreshToken',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.RefreshTokenRequest,
    auth_data_pb.RefreshTokenResponse,
    (request: auth_data_pb.RefreshTokenRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.RefreshTokenResponse.deserializeBinary
  );

  refreshToken(
    request: auth_data_pb.RefreshTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.RefreshTokenResponse>;

  refreshToken(
    request: auth_data_pb.RefreshTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.RefreshTokenResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.RefreshTokenResponse>;

  refreshToken(
    request: auth_data_pb.RefreshTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.RefreshTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/RefreshToken',
        request,
        metadata || {},
        this.methodDescriptorRefreshToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/RefreshToken',
    request,
    metadata || {},
    this.methodDescriptorRefreshToken);
  }

  methodDescriptorResetPassword = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/ResetPassword',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.ResetPasswordRequest,
    auth_data_pb.ResetPasswordResponse,
    (request: auth_data_pb.ResetPasswordRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.ResetPasswordResponse.deserializeBinary
  );

  resetPassword(
    request: auth_data_pb.ResetPasswordRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.ResetPasswordResponse>;

  resetPassword(
    request: auth_data_pb.ResetPasswordRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.ResetPasswordResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.ResetPasswordResponse>;

  resetPassword(
    request: auth_data_pb.ResetPasswordRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.ResetPasswordResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/ResetPassword',
        request,
        metadata || {},
        this.methodDescriptorResetPassword,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/ResetPassword',
    request,
    metadata || {},
    this.methodDescriptorResetPassword);
  }

  methodDescriptorChangePassword = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/ChangePassword',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.ChangePasswordRequest,
    auth_data_pb.ChangePasswordResponse,
    (request: auth_data_pb.ChangePasswordRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.ChangePasswordResponse.deserializeBinary
  );

  changePassword(
    request: auth_data_pb.ChangePasswordRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.ChangePasswordResponse>;

  changePassword(
    request: auth_data_pb.ChangePasswordRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.ChangePasswordResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.ChangePasswordResponse>;

  changePassword(
    request: auth_data_pb.ChangePasswordRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.ChangePasswordResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/ChangePassword',
        request,
        metadata || {},
        this.methodDescriptorChangePassword,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/ChangePassword',
    request,
    metadata || {},
    this.methodDescriptorChangePassword);
  }

  methodDescriptorUpdateUserProfile = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/UpdateUserProfile',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.UpdateUserProfileRequest,
    auth_data_pb.UpdateUserProfileResponse,
    (request: auth_data_pb.UpdateUserProfileRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.UpdateUserProfileResponse.deserializeBinary
  );

  updateUserProfile(
    request: auth_data_pb.UpdateUserProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.UpdateUserProfileResponse>;

  updateUserProfile(
    request: auth_data_pb.UpdateUserProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.UpdateUserProfileResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.UpdateUserProfileResponse>;

  updateUserProfile(
    request: auth_data_pb.UpdateUserProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.UpdateUserProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/UpdateUserProfile',
        request,
        metadata || {},
        this.methodDescriptorUpdateUserProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/UpdateUserProfile',
    request,
    metadata || {},
    this.methodDescriptorUpdateUserProfile);
  }

  methodDescriptorGetUserProfile = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/GetUserProfile',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.GetUserProfileRequest,
    auth_data_pb.GetUserProfileResponse,
    (request: auth_data_pb.GetUserProfileRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.GetUserProfileResponse.deserializeBinary
  );

  getUserProfile(
    request: auth_data_pb.GetUserProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.GetUserProfileResponse>;

  getUserProfile(
    request: auth_data_pb.GetUserProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.GetUserProfileResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.GetUserProfileResponse>;

  getUserProfile(
    request: auth_data_pb.GetUserProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.GetUserProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/GetUserProfile',
        request,
        metadata || {},
        this.methodDescriptorGetUserProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/GetUserProfile',
    request,
    metadata || {},
    this.methodDescriptorGetUserProfile);
  }

  methodDescriptorVerifyAccount = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/VerifyAccount',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.VerifyAccountRequest,
    auth_data_pb.VerifyAccountResponse,
    (request: auth_data_pb.VerifyAccountRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.VerifyAccountResponse.deserializeBinary
  );

  verifyAccount(
    request: auth_data_pb.VerifyAccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.VerifyAccountResponse>;

  verifyAccount(
    request: auth_data_pb.VerifyAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.VerifyAccountResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.VerifyAccountResponse>;

  verifyAccount(
    request: auth_data_pb.VerifyAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.VerifyAccountResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/VerifyAccount',
        request,
        metadata || {},
        this.methodDescriptorVerifyAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/VerifyAccount',
    request,
    metadata || {},
    this.methodDescriptorVerifyAccount);
  }

  methodDescriptorDeactivateAccount = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/DeactivateAccount',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.DeactivateAccountRequest,
    auth_data_pb.DeactivateAccountResponse,
    (request: auth_data_pb.DeactivateAccountRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.DeactivateAccountResponse.deserializeBinary
  );

  deactivateAccount(
    request: auth_data_pb.DeactivateAccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.DeactivateAccountResponse>;

  deactivateAccount(
    request: auth_data_pb.DeactivateAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.DeactivateAccountResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.DeactivateAccountResponse>;

  deactivateAccount(
    request: auth_data_pb.DeactivateAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.DeactivateAccountResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/DeactivateAccount',
        request,
        metadata || {},
        this.methodDescriptorDeactivateAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/DeactivateAccount',
    request,
    metadata || {},
    this.methodDescriptorDeactivateAccount);
  }

  methodDescriptorCreatePermission = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/CreatePermission',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.CreatePermissionRequest,
    auth_data_pb.CreatePermissionResponse,
    (request: auth_data_pb.CreatePermissionRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.CreatePermissionResponse.deserializeBinary
  );

  createPermission(
    request: auth_data_pb.CreatePermissionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.CreatePermissionResponse>;

  createPermission(
    request: auth_data_pb.CreatePermissionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.CreatePermissionResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.CreatePermissionResponse>;

  createPermission(
    request: auth_data_pb.CreatePermissionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.CreatePermissionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/CreatePermission',
        request,
        metadata || {},
        this.methodDescriptorCreatePermission,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/CreatePermission',
    request,
    metadata || {},
    this.methodDescriptorCreatePermission);
  }

  methodDescriptorListPermission = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/ListPermission',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.ListPermissionRequest,
    auth_data_pb.ListPermissionResponse,
    (request: auth_data_pb.ListPermissionRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.ListPermissionResponse.deserializeBinary
  );

  listPermission(
    request: auth_data_pb.ListPermissionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.ListPermissionResponse>;

  listPermission(
    request: auth_data_pb.ListPermissionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.ListPermissionResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.ListPermissionResponse>;

  listPermission(
    request: auth_data_pb.ListPermissionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.ListPermissionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/ListPermission',
        request,
        metadata || {},
        this.methodDescriptorListPermission,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/ListPermission',
    request,
    metadata || {},
    this.methodDescriptorListPermission);
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/CreateUser',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.CreateUserRequest,
    auth_data_pb.CreateUserResponse,
    (request: auth_data_pb.CreateUserRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.CreateUserResponse.deserializeBinary
  );

  createUser(
    request: auth_data_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.CreateUserResponse>;

  createUser(
    request: auth_data_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.CreateUserResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.CreateUserResponse>;

  createUser(
    request: auth_data_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.CreateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

  methodDescriptorListUser = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/ListUser',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.ListUserRequest,
    auth_data_pb.ListUserResponse,
    (request: auth_data_pb.ListUserRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.ListUserResponse.deserializeBinary
  );

  listUser(
    request: auth_data_pb.ListUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.ListUserResponse>;

  listUser(
    request: auth_data_pb.ListUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.ListUserResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.ListUserResponse>;

  listUser(
    request: auth_data_pb.ListUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.ListUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/ListUser',
        request,
        metadata || {},
        this.methodDescriptorListUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/ListUser',
    request,
    metadata || {},
    this.methodDescriptorListUser);
  }

  methodDescriptorRegisterDevice = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/RegisterDevice',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.RegisterDeviceRequest,
    auth_data_pb.RegisterDeviceResponse,
    (request: auth_data_pb.RegisterDeviceRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.RegisterDeviceResponse.deserializeBinary
  );

  registerDevice(
    request: auth_data_pb.RegisterDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.RegisterDeviceResponse>;

  registerDevice(
    request: auth_data_pb.RegisterDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.RegisterDeviceResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.RegisterDeviceResponse>;

  registerDevice(
    request: auth_data_pb.RegisterDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.RegisterDeviceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/RegisterDevice',
        request,
        metadata || {},
        this.methodDescriptorRegisterDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/RegisterDevice',
    request,
    metadata || {},
    this.methodDescriptorRegisterDevice);
  }

  methodDescriptorUnregisterDevice = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/UnregisterDevice',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.UnregisterDeviceRequest,
    auth_data_pb.UnregisterDeviceResponse,
    (request: auth_data_pb.UnregisterDeviceRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.UnregisterDeviceResponse.deserializeBinary
  );

  unregisterDevice(
    request: auth_data_pb.UnregisterDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.UnregisterDeviceResponse>;

  unregisterDevice(
    request: auth_data_pb.UnregisterDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.UnregisterDeviceResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.UnregisterDeviceResponse>;

  unregisterDevice(
    request: auth_data_pb.UnregisterDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.UnregisterDeviceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/UnregisterDevice',
        request,
        metadata || {},
        this.methodDescriptorUnregisterDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/UnregisterDevice',
    request,
    metadata || {},
    this.methodDescriptorUnregisterDevice);
  }

  methodDescriptorListDevice = new grpcWeb.MethodDescriptor(
    '/backend.auth.api.AuthService/ListDevice',
    grpcWeb.MethodType.UNARY,
    auth_data_pb.ListDeviceRequest,
    auth_data_pb.ListDeviceResponse,
    (request: auth_data_pb.ListDeviceRequest) => {
      return request.serializeBinary();
    },
    auth_data_pb.ListDeviceResponse.deserializeBinary
  );

  listDevice(
    request: auth_data_pb.ListDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_data_pb.ListDeviceResponse>;

  listDevice(
    request: auth_data_pb.ListDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_data_pb.ListDeviceResponse) => void): grpcWeb.ClientReadableStream<auth_data_pb.ListDeviceResponse>;

  listDevice(
    request: auth_data_pb.ListDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_data_pb.ListDeviceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.auth.api.AuthService/ListDevice',
        request,
        metadata || {},
        this.methodDescriptorListDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.auth.api.AuthService/ListDevice',
    request,
    metadata || {},
    this.methodDescriptorListDevice);
  }

}

